config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :articles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :youtube, only: :show
  resources :about, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :content
  has_one_attached :photo
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/youtube.rb
class Youtube
  include ActiveModel::Model
  include ActiveModel::Attributes
  include GlobalID::Identification
  include ActionText::Attachable

  attribute :id

  def self.find(id)
    new(id: id)
  end

  def thumbnail_url
    "http://i3.ytimg.com/vi/#{id}/maxresdefault.jpg"
  end

  def to_trix_content_attachment_partial_path
    "youtubes/thumbnail"
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
    @categories = Category.all
    @main_article = Article.last
    @category_id = params["category_id"]
    @articles = Article.where(category_id: @category_id) if params["category_id"]
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Artigo atualizado com sucesso!" }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :summary, :photo, :creation_date, :category_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @articles = Article.last(3)
    @categories = Category.all
  end
end

app/controllers/youtube_controller.rb
class YoutubeController < ApplicationController
  def show
    @youtube = Youtube.new(id: params[:id])
    render json: {
      sgid: @youtube.attachable_sgid,
      content: render_to_string(partial: "youtubes/thumbnail", locals: { youtube: @youtube }, formats: [:html])
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%# <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
    <% if local_assigns[:in_gallery] %>
        <%= cl_image_tag blob.key, width: 564, c_limit: true %>
    <% else %>
        <%= cl_image_tag blob.key, width:564, c_limit: true %>
    <% end %>

  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <%# <span class="attachment__name"><%= blob.filename</span> %>
      <%# <span class="attachment__size"><%= number_to_human_size blob.byte_size %><%#</span> %>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

    <strong>Body:</strong>
      <%= article.content %>
</div>

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  <h3 class=" text-gray-600 border-b text-2xl border-gray-600 mt-10 mb-2">Título</h3>
    <%= f.input_field :title, placeholder: "Título", class: "article-form__title-input text-4xl",input_html: {class:"article-form__title-input"}  %>
    <h3 class="text-gray-600 border-b text-2xl border-gray-600 mt-10 mb-2">Epítome</h3>
    <%= f.input_field :summary, placeholder: "Escrever uma epítome do texto, caso haja...", class: "article-form__summary-input" %>
    <div data-controller="image-preview" class="mt-10 text-center">
      <%= f.input :photo, as: :file, input_html: {direct_upload: true, data: {image_preview_target:"input", action:"change->image-preview#preview"},class:"article-form__photo-input"}, label:'Foto de Capa', label_html:{class:"bg-purple-900 p-3 rounded-md mb-3"}%>
      <% if @article.photo.attached? %>
      <%= cl_image_tag @article.photo.key,data: {image_preview_target:"preview"} ,width: 564, crop: :fill %>
        <% else %>
      <% end %>
    </div><!--image-preview-->
    <h3 class="text-gray-600 border-b text-2xl border-gray-600 mt-10 mb-2">Data de Publicação</h3>
    <%= f.input_field :creation_date, as: :date, html5: true,class:"bg-black rounded-xl w-32 text-center"%>
    <h3 class="text-gray-600 border-b text-2xl border-gray-600 mt-10 mb-2">Categoria</h3>
    <%= f.input_field :category_id, class:"bg-black rounded-xl w-32 text-center mb-2", collection: Category.all.map {|category| ["#{category.title}", category.id.to_i]}%>
    <h3 class="text-gray-600 border-b text-2xl border-gray-600 mt-10 mb-2">Texto do artigo</h3>
    <div data-controller="trix-navbar">
      <%= f.rich_text_area :content, placeholder: "Texto do artigo..." %>
    </div><!--trix-navbar-->
  </div><!--form-inputs-->

  <div class="form-actions">
    <%= f.button :submit, "Salvar",class:"article-form__save-button mt-3" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1 class="text-6xl mb-5">Editar Artigo</h1>

<div class="article-form__secondary-links-div">

  <%= link_to "Voltar para artigo", @article, class: "article-form__secondary-links"%> |
  <%= link_to "Todos os artigos", articles_path , class: "article-form__secondary-links"%>
</div><!--article-form__secondary-links-div-->
<%= render "form", article: @article %>

<br>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>




<div class="main-article__div w-full-a m-auto">
  <div class="main-article__text-div">
    <h2><%= @main_article.title %></h2>
    <p class = "text-base"><%= @main_article.summary %></p>
      <%= link_to @main_article, :class=>"article-show__goback-button" do %>
        Ler agora <i class="fa-solid fa-arrow-right"></i>
      <% end %>
  </div>
  <div class="main-article__photo-div">
    <% if @main_article.photo.attached?  %>
        <%= cl_image_tag @main_article.photo.key, width: 564, crop: :fill, :class =>"rounded-md" %>
    <% end %>
  </div>
</div>

<div class="articles-index__all-articles-div">



  <% @articles.each do |article| %>

    <div class="article-card__card-div">
      <% if article.photo.attached?  %>
          <%= cl_image_tag article.photo.key, width: 243, crop: :fill, :class =>"rounded-md" %>
      <% end %>
      <div class="article-card__text-div">
      <h3><%= article.title %></h3>
      <div class="article-card__category-tag-div">
        <span ><%= (Category.where(id: article.category_id))[0].title %></span>
      </div>


        <%= link_to article, :class=>"article-show__goback-button" do %>
          Ler agora <i class="fa-solid fa-arrow-right"></i>
        <% end %>
      </div>
    </div>

  <% end %>
</div>

app/views/articles/new.html.erb
<h1 class="text-6xl mb-5">Novo Artigo</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Voltar para artigos", root_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="article-content">
  <div class="article-show__shortcuts-div">
    <div class="mb-11">
      <%= link_to articles_path, :class=>"article-show__goback-button" do %>
        <i class="fa-solid fa-arrow-left"></i>  Voltar
      <% end %>
    </div> <!-- mb-11 -->
    <div class="flex gap-6">
        <%= link_to edit_article_path(@article), :class=>"article-show__editor-button" do %>
          <i class="fa-solid fa-pencil fa-lg" style="color: #dedede;"></i>
        <% end %>
        <%= link_to @article, method: :delete, :class=>"article-show__editor-button" do %>
          <i class="fa-solid fa-trash fa-lg" style="color: #dedede;"></i>
        <% end %>
    </div><!--flex gap-6-->
  </div><!--article-show__shortcuts-div-->
  <div class="mb-6">
    <span class="article-show__category-tag"><%= Category.find(@article.category_id).title %></span>
    <span class="article-show__date-tag"><%= @article.creation_date.strftime('%d.%m.%Y') %></span>
  </div><!--mb-6-->

  <div class="article-show__column-header">
    <h1 class="text-4xl mb-5"><%= @article.title %></h1>
    <p class="article-show__summary"><%= @article.summary %></p>
    <div class="text-center">
      <% if @article.photo.attached?  %>
        <%= cl_image_tag @article.photo.key, width: 422, crop: :fill, :class =>"rounded-md" %>
      <% end %>
      <hr>
    </div><!--text-center-->
  </div><!--article-show__column-header-->

  <div class="article-show__content-div">
    <p><%= @article.content %>  </p>
      <hr style="width:100%;margin-left:auto;margin-right:auto;">
  </div><!--article-show__content-div-->

</div><!--article-content-->

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RahttegaBlog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <div class="mr-auto ml-auto content-part">
    <%= yield %>
  </div>
  <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<!--Area do Título-->
<div class="flex w-full-a justify-between bg-gray-900 p-4 rounded-lg m-auto">
  <div>
    <%= image_tag "rattegabranco.png", style:"width:300px;"%>
    <p>Artigos sobre luz e sombras, sobre nada e tudo</p>
    <%= link_to articles_path, :class=>"article-show__goback-button" do %>
        Ver Artigos
    <% end %>
  </div>
  <div>
    <%= image_tag "bookshelf.jpg",style:"width:500px;",class:"grayscale"%>
  </div>
</div>





<!--Artigos Mais Recentes-->
<h2 class="text-center mt-24">Textos mais recentes</h2>

<% unless @articles[0].nil? %>
  <div class="flex w-full-a justify-between p-8 m-auto items-center">
    <div class="w-2/5">
      <h3><%= @articles[0].title %></h3>
      <p><%= @articles[0].summary %></p>
    </div>
    <div>
      <% if @articles[0].photo.attached?  %>
        <%= cl_image_tag @articles[0].photo.key, width: 461, crop: :fill, :class =>"rounded-md" %>
      <% end %>
    </div>
  </div>
<% end %>

<% unless @articles[1].nil? %>
  <div class="flex w-full-a justify-between p-8 m-auto items-center">
    <div>
      <% if @articles[1].photo.attached?  %>
        <%= cl_image_tag @articles[1].photo.key, width: 461, crop: :fill, :class =>"rounded-md" %>
      <% end %>
    </div>
    <div class="w-2/5">
      <h3><%= @articles[1].title %></h3>
      <p><%= @articles[1].summary %></p>
    </div>
  </div>
<% end %>
<% unless @articles[2].nil? %>
  <div class="flex w-full-a justify-between p-8 m-auto items-center">
    <div class="w-2/5">
      <h3><%= @articles[2].title %></h3>
      <p><%= @articles[2].summary %></p>
    </div>
    <div>
      <% if @articles[2].photo.attached?  %>
        <%= cl_image_tag @articles[2].photo.key, width: 461, crop: :fill, :class =>"rounded-md" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="h-24  mt-5">
<div class="flex justify-between w-full-a m-auto ">
  <div>
    <%= image_tag "rattegabranco.png", style:"width:200px;"%>
  </div>

  <div class="flex items-center gap-5 grayscale">
    <%= image_tag "youtube-icon.png", style:"width:30px;height:30px;"%>
    <%= image_tag "x-icon.png", style:"width:30px;height:30px;"%>
    <%= image_tag "instagram-icon.png", style:"width:30px;height:30px;"%>
  </div>
</div>
</footer>

app/views/shared/_navbar.html.erb
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>

<nav class="h-10 mb-5 flex" style="background-color:#48484875;">
  <div class="flex w-full-a m-auto justify-between">
    <%= link_to "Rahttega", root_path, class: "navbar-brand" %>
    <div class="flex gap-5">
      <div @click.away="open = false" class="relative" x-data="{ open: false }">
        <button @click="open = !open" class="flex flex-row items-center w-full px-4 py-2 mt-2 text-sm font-semibold text-left bg-transparent rounded-lg  md:w-auto md:inline md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline">
          <span>Artigos</span>
          <svg fill="currentColor" viewBox="0 0 20 20" :class="{'rotate-180': open, 'rotate-0': !open}" class="inline w-4 h-4 mt-1 ml-1 transition-transform duration-200 transform md:-mt-1"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </button>
        <div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="absolute right-0 w-full mt-2 origin-top-right rounded-md shadow-lg md:w-48  z-50">
          <div class="px-2 py-2 bg-white rounded-md shadow dark-mode:bg-gray-800">
            <%= link_to 'Todos os Artigos', articles_path, class: 'text-gray-900 block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline'  %>
            <% Category.all.each do |category| %>
              <%= link_to articles_path(category_id: category.id), :class=>"text-gray-900 block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" do %>
                <span><%= category.title %></span>
              <% end %>
            <%end%>
            </div>
        </div>
      </div>
      <%= link_to 'Sobre', about_index_path, class: 'text-gray-50 block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline'  %>
      <%= link_to 'Novo Artigo', new_article_path, class: 'text-gray-50 block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline'  %>
    </div>
</div>
</nav>

app/views/youtubes/_thumbnail.html.erb
<div class="trix-editor__youtube-thumb-div">
  <%= image_tag youtube.thumbnail_url, style: "max-width:400px" %>
</div>

app/views/youtubes/_youtube.html.erb
<div>
  <iframe id="ytplayer" type="text/html" width="564" height="318" src="https://www.youtube.com/embed/<%= youtube.id %>" frameborder="0"></iframe>
</div>